name: 'Personal Project Manager'
description: 'Converts ProjectV2 cards to issues and assigns to a user account.'
branding:
  icon: book
  color: blue

inputs:
  token:
    description: 'The GitHub token to use for authentication.'
    required: true
  projectNumber:
    description: 'The number of the project to manage.'
    required: true
  owner:
    description: 'The owner of the repository where the project is located.'
    required: true
  repository:
    description: 'The name of the repository where the project is located.'
    required: true
  username:
    description: 'The username to assign issues to.'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
